### ISSUE TITLE
Get rid of id properties

### ISSUE THREAD

**Issue by otacke** [msdlt/h5p.LinkedImageSwap#3]
Why don't you use `self.$imageElement` but search for the element?

You should avoid using the id property of HTML elements in general. It's fine if you only think of your own content type as a standalone version, but it will break if you put more than one of them into compound content types such as H5P Column.

https://github.com/msdlt/h5p.LinkedImageSwap/blob/48d5259272acc6d2289d23b217bd55d6342511de/linked-image-swap.js#L191-L192

**Comment by otacke** [comment]
@theotherdy Hope I am not bugging you :-) I simply had a glance at your code yesterday and stumbled across those. I could have a more thorough look this weekend if you don't mind.

**Comment by theotherdy** [comment]
No, not at all - it's very useful indeed. - thank you! Any feedback very welcome - particularly if you had any ideas for the[` !important` I have found myself having to use in the css to get rid of margins](https://github.com/msdlt/h5p.LinkedImageSwap/blob/89154dd522cd8726dba857e71e353a330a0e4b61/linked-image-swap.css#L16), or any tips for how to get FontAwesome to work instead of the css solution that doesn't seem to antialias well :)
